# Generated by Django 5.1.5 on 2025-03-17 17:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BruteForceDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Detection_date_and_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Attackers_IP', models.GenericIPAddressField()),
                ('attempted_username', models.CharField(default='blank', max_length=255)),
                ('attempted_password', models.CharField(default='blank', max_length=255)),
                ('Number_of_attempts', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SQLInjectionDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Detection_date_and_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Attackers_IP', models.CharField(max_length=50)),
                ('attempted_username', models.CharField(default='blank', max_length=255)),
                ('attempted_password', models.CharField(default='blank', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DOSDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Detection_date_and_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Attackers_IP', models.CharField(max_length=50, null=True)),
                ('Attack_type', models.CharField(max_length=75, null=True)),
                ('Traffic_rate', models.FloatField(null=True)),
                ('Details', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'DoS Detection',
                'verbose_name_plural': 'DoS Detections',
                'unique_together': {('Attackers_IP', 'Attack_type')},
            },
        ),
    ]
